# render.yaml (para el servicio backend-render-videos)

services:
  - type: web
    name: backend-render-videos # Asegúrate que el nombre coincida con tu servicio
    env: python
    plan: free # El plan gratuito puede ser lento para renderizar. Considera un plan de pago si es necesario.
    
    # NUEVO: Usar el script de construcción para instalar ffmpeg y las dependencias de Python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app --timeout 120" # Aumentar el timeout para Gunicorn

    # Las mismas variables de entorno que el otro backend
    envVars:
      - key: GCS_BUCKET_NAME
        sync: false
      - key: GCS_CREDENTIALS_JSON
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.4
