# render.yaml
# Para desplegar en Render.com usando Render Blueprints
services:
  - type: web
    name: video-json-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.19 # O la versión de Python que prefieras y que Render soporte
      - key: FLASK_ENV
        value: production
      # Aquí debes añadir tu clave de API de Google AI si usas Gemini/Vertex AI
      # - key: GOOGLE_API_KEY
      #   value: tu_api_key_aqui # ¡IMPORTANTE: Configura esto en Render de forma segura!
    healthCheckPath: /
    # Puedes ajustar el plan y instanceCount según tus necesidades
    # plan: free
    # instanceCount: 1
